### PR TITLE
Sr branch 1

### PR DESCRIPTION
**Pull request by SharifRashed**
#### Changes Made

1. Added to file `Animal.js` to `animals` directory.
1. Modified file `Animal.js` to include a user to to be able to choose an owner for an animal.
   

#### Steps to Review

1. Checkout this branch locally.
   ```
   git fetch --all
   git checkout sr-branch-1
   ```
2. Open a new Terminal tab (⌘T) and navigate to the server directory.
3. Test app functionality.
   > Instructions for how reviewer can test functionality, and detailed description of what the expected outcome is.
   > Example: When user does BLANK, then BLANK should happen.

### CODE REVIEW

**Comment by SharifRashed** [comment]
Syntax error- page will not refresh

**Review by user1hunter — APPROVED** [review]
Looks good

**Review by DougSilvera — APPROVED** [review]
excellent

**Review by Jennifer-Blue-Williams — APPROVED** [review]
Great job!! Works wonderfully.

**Pull request merged**
