### PR TITLE
Bw showcaretakers

### PR DESCRIPTION
**Pull request by Jennifer-Blue-Williams**
1. Added to file "Animals.js" in the "Animals" folder.
2. I modified Animals.js to include the ability to see the caretaker(s) that have been assigned to an animal.

### CODE REVIEW

**Review by DougSilvera — APPROVED** [review]
looks good

**Comment by user1hunter** [comment]
Looks good to me

**Review by user1hunter — APPROVED** [review]
Approved

**Review by SharifRashed — APPROVED** [review]
Looks good, glad you were able to add the .join to fix what was needed to be fixed.

**Pull request merged**
